---
project:
  name: PHPUnit
  code_name: phpunit
  website: https://www.phpunit.de/
  repository: https://github.com/JulienBreux/phpunit-docker.git
  author:
    name: Julien Breux
    email: julien.breux@gmail.com
image:
  base: composer/composer:php7
xdebug:
  version: 2.4.0
php:
  version: 7.0
versions:
- 5.4.2
- 5.4.1
- 5.4.0
- 5.3.4
- 5.3.3
- 5.3.2
- 5.3.1
- 5.3.0
- 5.1.0
- 5.0.10
- 5.0.9
- 5.0.8
- 5.0.7
- 5.0.6
- 5.0.5
- 5.0.4
- 5.0.3
- 5.0.2
- 5.0.1
- 5.0.0
- 4.8.16
- 4.8.5
- 4.8.4
- 4.8.3
- 4.7.7
- 4.6.10
- 4.6.6
